projects:
  ToDo:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: 45l3avxffrhlbeenhs34guq4ta
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://x4ip6jm2xvetxcs5y2aieuidpy.appsync-api.us-east-1.amazonaws.com/graphql
