// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://x4ip6jm2xvetxcs5y2aieuidpy.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-sr36m5zglrcpnjrud7zbd5zxa4",
  aws_cognito_identity_pool_id:
    "us-east-1:e75a032a-469e-4014-ad44-8c805e013e4d",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_qOq0N8Q5L",
  aws_user_pools_web_client_id: "4cc5stkafsqlo9k0uocqf0v3j2"
};

export default awsmobile;
